#!/bin/bash
# Reproduce ALL alignn2_radius entries. pip install alignn first.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
bash "$HERE/run_avg_elec_mass.sh"
bash "$HERE/run_avg_hole_mass.sh"
bash "$HERE/run_bulk_modulus_kv.sh"
bash "$HERE/run_dfpt_piezo_max_dielectric.sh"
bash "$HERE/run_dfpt_piezo_max_dij.sh"
bash "$HERE/run_ehull.sh"
bash "$HERE/run_encut.sh"
bash "$HERE/run_epsx.sh"
bash "$HERE/run_epsy.sh"
bash "$HERE/run_epsz.sh"
bash "$HERE/run_exfoliation_energy.sh"
bash "$HERE/run_formation_energy_peratom.sh"
bash "$HERE/run_kpoint_length_unit.sh"
bash "$HERE/run_magmom_oszicar.sh"
bash "$HERE/run_max_efg.sh"
bash "$HERE/run_mbj_bandgap.sh"
bash "$HERE/run_mepsx.sh"
bash "$HERE/run_mepsy.sh"
bash "$HERE/run_mepsz.sh"
bash "$HERE/run_n_Seebeck.sh"
bash "$HERE/run_n_powerfact.sh"
bash "$HERE/run_optb88vdw_bandgap.sh"
bash "$HERE/run_optb88vdw_total_energy.sh"
bash "$HERE/run_shear_modulus_gv.sh"
bash "$HERE/run_slme.sh"
bash "$HERE/run_spillage.sh"
# --- MLFF (force-field) entries ---
bash "$HERE/run_mlff_matpes.sh"
bash "$HERE/run_mlff_alignn_ff_db.sh"
bash "$HERE/run_mlff_mptrj.sh"
bash "$HERE/run_mlff_mlearn_Cu.sh"
bash "$HERE/run_mlff_mlearn_Ni.sh"
bash "$HERE/run_mlff_mlearn_Li.sh"
bash "$HERE/run_mlff_mlearn_Ge.sh"
bash "$HERE/run_mlff_mlearn_Mo.sh"
bash "$HERE/run_mlff_mlearn_Si.sh"
# --- Additional JARVIS datasets ---
bash "$HERE/run_mxene275_formation_energy.sh"
bash "$HERE/run_polymer_genome_gga_gap.sh"
bash "$HERE/run_c2db_gap.sh"
bash "$HERE/run_twod_matpd_bandgap.sh"
bash "$HERE/run_omdb_bandgap.sh"
bash "$HERE/run_pdbbind_binding_affinity.sh"
# --- Spectra entries ---
bash "$HERE/run_ir.sh"
bash "$HERE/run_dielectric.sh"
